export type Category = "Skin" | "Hair" | "Makeup";

export const categories: Category[] = ["Skin", "Hair", "Makeup"];

export type ConcernId =
  // skin
  | "hydration"
  | "barrier"
  | "brightening"
  | "texture"
  | "pores"
  | "firmness"
  // hair
  | "frizz"
  | "scalp"
  | "damage"
  | "volume"
  // makeup
  | "longwear"
  | "coverage"
  | "lipcare";

export interface Concern {
  id: ConcernId;
  label: string;
  blurb: string;
  category: Category;
}

export const concerns: Concern[] = [
  { id: "hydration", label: "Hydration", blurb: "Tight by mid-afternoon", category: "Skin" },
  {
    id: "barrier",
    label: "Barrier & sensitivity",
    blurb: "Reacts to strong actives",
    category: "Skin",
  },
  {
    id: "brightening",
    label: "Brightening",
    blurb: "Post-acne marks, uneven tone",
    category: "Skin",
  },
  { id: "texture", label: "Texture", blurb: "Rough patches around the chin", category: "Skin" },
  { id: "pores", label: "Pores & oil", blurb: "Shine through the T-zone", category: "Skin" },
  { id: "firmness", label: "Firmness", blurb: "Early loss of bounce", category: "Skin" },

  { id: "frizz", label: "Frizz", blurb: "Humidity lifts the surface", category: "Hair" },
  { id: "scalp", label: "Scalp care", blurb: "Flaking at the crown", category: "Hair" },
  { id: "damage", label: "Damage & split ends", blurb: "Colour-treated mid-lengths", category: "Hair" },
  { id: "volume", label: "Volume", blurb: "Flat by the second day", category: "Hair" },

  { id: "longwear", label: "Long wear", blurb: "Melts in Singapore heat", category: "Makeup" },
  { id: "coverage", label: "Coverage", blurb: "Evening out redness", category: "Makeup" },
  { id: "lipcare", label: "Lip care", blurb: "Dry, flaking lips", category: "Makeup" },
];

export type SkinType = "Oily" | "Combination" | "Dry" | "Normal";

export const skinTypes: SkinType[] = ["Oily", "Combination", "Dry", "Normal"];

export type Step =
  | "Cleanse"
  | "Treat"
  | "Hydrate"
  | "Protect"
  | "Weekly"
  | "Wash"
  | "Condition"
  | "Style"
  | "Base"
  | "Colour";

export interface Product {
  id: string;
  name: string;
  brand: string;
  category: Category;
  step: Step;
  vessel: "cleanser" | "vitc" | "moisturiser" | "spf" | "mask" | "shampoo" | "hairoil" | "foundation" | "lipstick";
  /** Real product shot from the member's order history. */
  image?: string;
  covers: ConcernId[];
  /** Where it sits in the routine. */
  routine: string;
  /** Actives the model reasons about when checking conflicts. */
  actives: string[];
  purchased: string;
}

const IMG = "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/";

/** Pulled from the member's Sephora order history. */
export const pastPurchases: Product[] = [
  // Skin
  {
    id: "indie-wash",
    name: "Purifying Face Wash (125ml)",
    brand: "Indie Lee",
    category: "Skin",
    step: "Cleanse",
    vessel: "cleanser",
    image: `${IMG}1_Product_702685964737-Indie-Lee-Purifying-Face-Wash-125ml_bb53c7b160b369e836b1e335bb420e16687dea69_1709021953.png`,
    covers: ["barrier"],
    routine: "First step, morning and night. Low-foam, keeps the barrier intact.",
    actives: [],
    purchased: "Oct 2020",
  },
  {
    id: "indie-toner",
    name: "CoQ-10 Toner (125ml)",
    brand: "Indie Lee",
    category: "Skin",
    step: "Treat",
    vessel: "vitc",
    image: `${IMG}1_Product_702685964492-Indie-Lee-CoQ-10-Toner-125ml_2f17dc37ed6fa81f6e884fca9a0c98c9f2b036c8_1709021939.png`,
    covers: ["brightening"],
    routine: "Swept on after cleansing, morning and night.",
    actives: ["antioxidant"],
    purchased: "Oct 2020",
  },
  {
    id: "ddg-peel",
    name: "Alpha Beta Extra Strength Daily Peel",
    brand: "Dr. Dennis Gross",
    category: "Skin",
    step: "Treat",
    vessel: "vitc",
    image: `${IMG}Alpha_Beta_Extra_Strength_Daily_Peel__1bfdb8f9ab1015154087c98e415ab37f6c257f3c_1557823515.png`,
    covers: ["texture", "pores"],
    routine: "Two-step acid pad in the evening. Strong — never on the same night as retinol.",
    actives: ["aha", "bha", "acid"],
    purchased: "Oct 2020",
  },
  {
    id: "sdj-bomdia",
    name: "Bom Dia Bright™ AHA BHA Body Wash (90ml)",
    brand: "Sol de Janeiro",
    category: "Skin",
    step: "Cleanse",
    vessel: "cleanser",
    image: `${IMG}1_Product_810912032699-Sol-De-Janeiro-Bom-Dia-Bright-Clarify_36c03745cb80fd6df1058b17906c3a0ef281c5bc_1724049639.png`,
    covers: ["texture"],
    routine: "Body cleanse, a few times a week for smoother arms and back.",
    actives: ["aha", "bha", "acid"],
    purchased: "Aug 2026",
  },
  {
    id: "sdj-drench",
    name: "Delícia Drench™ Jet Set",
    brand: "Sol de Janeiro",
    category: "Skin",
    step: "Hydrate",
    vessel: "moisturiser",
    image: `${IMG}1_Product_810912035980-Sol-De-Janeiro-Delicia-Drench-Jet-Set_3d988f2c409ab8466f1970bc6cc1a83c68a5beb5_1735301078.png`,
    covers: ["hydration"],
    routine: "Body moisture straight out of the shower.",
    actives: [],
    purchased: "Aug 2026",
  },
  {
    id: "kopari-wash",
    name: "Coconut Hydrating Body Wash (266ml)",
    brand: "Kopari Beauty",
    category: "Skin",
    step: "Cleanse",
    vessel: "cleanser",
    image: `${IMG}1_Product_850004184301-Kopari-Coconut-Hydrating-Body-Wash-26_0006c911936aa3393f76093ac4becc12d7e4c924_1710237045.png`,
    covers: ["hydration"],
    routine: "Gentle daily body wash on non-exfoliating days.",
    actives: [],
    purchased: "Jul 2021",
  },

  // Hair
  {
    id: "ouai-bond",
    name: "Bond Repair Balm (142ml)",
    brand: "OUAI",
    category: "Hair",
    step: "Condition",
    vessel: "shampoo",
    image: `${IMG}1_Product_815402022488-Ouai-Bond-Repair-Balm-142ml_97fae21a9444de5e9b3f0c69d1c0d4a21ef5178e_1772535386.png`,
    covers: ["damage"],
    routine: "Mid-lengths to ends after every wash to rebuild bonds.",
    actives: ["protein", "bond-builder"],
    purchased: "Aug 2026",
  },
  {
    id: "olaplex3",
    name: "No.3 Hair Perfector™ (100ml)",
    brand: "Olaplex",
    category: "Hair",
    step: "Condition",
    vessel: "shampoo",
    image: `${IMG}1_Product_850018802840-Olaplex-No-3-Hair-Perfector-Treatment_4563fd40b760adf7ff8f2db38b8aec2e3e334118_1742558310.png`,
    covers: ["damage"],
    routine: "Weekly pre-wash treatment on damp hair, 10 minutes minimum.",
    actives: ["bond-builder"],
    purchased: "Oct 2019",
  },
  {
    id: "briogeo-cond",
    name: "Don't Despair, Repair!™ Super Moisture Conditioner",
    brand: "Briogeo",
    category: "Hair",
    step: "Condition",
    vessel: "shampoo",
    image: `${IMG}1_Product_644216873586-Briogeo-Don-t-Despair-Repair-Super-Mo_2f835f64622e0f744e1b0b7663a8a6e102ace666_1709190789.png?o=clean-planet-aware`,
    covers: ["damage"],
    routine: "Rich conditioner for dry, colour-treated mid-lengths.",
    actives: ["protein"],
    purchased: "Jul 2021",
  },
  {
    id: "de-silkamino",
    name: "Silkamino™ Mega-Moisturizing Masker (210ml)",
    brand: "Drunk Elephant",
    category: "Hair",
    step: "Condition",
    vessel: "hairoil",
    image: `${IMG}1_Product_812343032828-Drunk-Elephant-Silkamino-Mega-Moistur_9d09aacfc4dd0a62db1f822ee106fc19cc5bcc2d_1730894335.png?o=clean`,
    covers: ["frizz", "damage"],
    routine: "Weekly mask, five minutes on the ends before rinsing.",
    actives: ["amino acids"],
    purchased: "Nov 2022",
  },
  {
    id: "tangle-teezer",
    name: "The Ultimate Detangler",
    brand: "Tangle Teezer",
    category: "Hair",
    step: "Style",
    vessel: "hairoil",
    image: `${IMG}1_Product_193244_20Tangle_20Teezer_20Wet_20Detangler_20Millenial_20Pink_19d985861a0065d7106b7f0d79627e1d67843e06_1532511676.png`,
    covers: [],
    routine: "Detangles wet hair without snapping fragile ends.",
    actives: [],
    purchased: "Oct 2020",
  },
  {
    id: "ghd-brush",
    name: "Ceramic Vented Radial Brush (Size 3)",
    brand: "GHD",
    category: "Hair",
    step: "Style",
    vessel: "hairoil",
    image: `${IMG}33563_GHD_WEB_b116abcd30e7056b43440e76a128c89e895fb6f0_1523779655.png`,
    covers: ["volume"],
    routine: "Blow-dry brush for lift at the roots.",
    actives: [],
    purchased: "Feb 2023",
  },

  // Makeup
  {
    id: "fenty-stix",
    name: "Match Stix Matte Contour Skinstick (Amber)",
    brand: "Fenty Beauty",
    category: "Makeup",
    step: "Base",
    vessel: "foundation",
    image: `${IMG}26130_Fenty_MatchStixMatteSkinstickAmber_WEB_4f8f3445fe1e6bebc41debc04edbb0f8fc1a2cdf_1523778026.png`,
    covers: ["coverage"],
    routine: "Cream contour tapped over base, blended with fingers.",
    actives: [],
    purchased: "Feb 2023",
  },
  {
    id: "burts-lip",
    name: "Moisturizing Lip Balm (Vanilla Bean)",
    brand: "Burt's Bees",
    category: "Makeup",
    step: "Colour",
    vessel: "lipstick",
    image: `${IMG}1_Product_792850026759-Burt-s-Bees-Moisturizing-Lip-Balm-Van_86cdccf3b388564e14d88778d7311cf8dcfd9190_1709022146.png`,
    covers: ["lipcare"],
    routine: "Lip prep morning and night, and under colour.",
    actives: [],
    purchased: "Oct 2021",
  },
  {
    id: "shiseido-brush",
    name: "Yane Hake Precision Eye Brush",
    brand: "Shiseido",
    category: "Makeup",
    step: "Colour",
    vessel: "foundation",
    image: `${IMG}1_Product_199403_20Shiseido_20Yane_20Hake_20Precision_20Eye_20Brush_20Default_c06adbf977f36b43937d27dfcfddae0b9e682625_1535014382.png`,
    covers: [],
    routine: "Angled brush for shadow and liner detail.",
    actives: [],
    purchased: "Nov 2022",
  },
];

/** Shelf the member starts with — her most recent, still-in-rotation buys. */
export const defaultShelf = [
  "indie-wash",
  "indie-toner",
  "sdj-drench",
  "ouai-bond",
  "briogeo-cond",
  "fenty-stix",
  "burts-lip",
];


export const defaultProfile = {
  name: "Emily",
  skinType: "Combination" as SkinType,
  concerns: [
    "hydration",
    "barrier",
    "brightening",
    "texture",
    "frizz",
    "scalp",
    "longwear",
    "lipcare",
  ] as ConcernId[],
  /** What she redeems most — used when there is no gap to close. */
  enjoys: ["hydration", "coverage"] as ConcernId[],
};

export interface Reward {
  id: string;
  name: string;
  brand: string;
  category: Category;
  points: number;
  tier: "All members" | "Gold & Black";
  covers: ConcernId[];
  vessel: number;
  /** Product shot from the Beauty Pass catalogue. */
  image?: string;
  /** Where it would sit in her routine. */
  routine: string;
  /** Shelf products it layers with. */
  pairsWith: string[];
  /** Skin types this is a poor match for. */
  avoidFor?: SkinType[];
  avoidReason?: string;
  /** Actives already on the shelf that clash. */
  conflictsWith?: string[];
  conflictReason?: string;
  caution?: string;
  /** Editor's note from the catalogue. */
  blurb?: string;
}

/** Real Beauty Pass Rewards Boutique catalogue (demo copy of a live redeemables feed). */
export const rewardCatalogue: Reward[] = [
  {
    id: "pixi-glow-tonic-exfoliating-toner",
    name: "Glow Tonic Exfoliating Toner (15 ml)",
    brand: "Pixi",
    category: "Skin",
    points: 100,
    tier: "All members",
    covers: ["texture", "brightening", "pores"],
    vessel: 0,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_885190821044-Pixi-Glow-Tonic-Exfoliating-Toner-15-ml-Default_c7bca4a96c14119158ef21870d8050245fc5f0d0_1646046005.png",
    routine: "Sweep over cleansed skin using a cotton pad in the evening before serums.",
    pairsWith: ["cleanser", "moisturiser", "spf"],
    avoidFor: ["Dry"],
    avoidReason: "Contains 5% glycolic acid which may exacerbate dry, flake-prone skin.",
    conflictsWith: ["retinol", "salicylic", "acid"],
    conflictReason: "Layering multiple strong exfoliating acids or retinoids increases irritation risk.",
    caution: "Always follow with daily broad-spectrum SPF as AHA increases sun sensitivity.",
    blurb: "The Pixi Glow Tonic™ is a highly concentrated, invigorating facial toner that deeply cleans pores by sweeping away excess oil and impurities.",
  },
  {
    id: "ouai-anti-frizz-cr-me",
    name: "Anti-Frizz Crème (30ml)",
    brand: "OUAI",
    category: "Hair",
    points: 100,
    tier: "All members",
    covers: ["frizz", "hydration"],
    vessel: 1,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_815402025809-Ouai-Anti-Frizz-Creme-30ml-Default_81fd1d12f1f91f34fe0563a497ff41d948c075ec_1708689426.png",
    routine: "Work a 5p-sized amount through damp or dry mid-lengths and ends before styling.",
    pairsWith: ["shampoo", "conditioner"],
  },
  {
    id: "fresh-soy-face-cleanser",
    name: "Soy Face Cleanser (15ml)",
    brand: "FRESH",
    category: "Skin",
    points: 100,
    tier: "All members",
    covers: ["hydration", "barrier"],
    vessel: 2,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_809280157806-Fresh-Soy-Face-Cleanser-15ml-Default_12dda30e21775824a625063b10ad895e01c44767_1645325342.png",
    routine: "Massage onto wet skin morning and evening, then rinse thoroughly with warm water.",
    pairsWith: ["cleanser", "moisturiser", "spf"],
    blurb: "Our best-selling universal face wash that’s proven to maintain skin’s pH while also cleansing, softening, and hydrating all skin types & tones.",
  },
  {
    id: "ouai-hair-curl-cr-me",
    name: "Hair Curl Crème (30 ML)",
    brand: "OUAI",
    category: "Hair",
    points: 100,
    tier: "All members",
    covers: ["frizz", "hydration"],
    vessel: 3,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_815402020613-Ouai-Hair-Curl-Creme-30-ML-Default_faee32096a35fb3e5a9ad8760a738415792e75d6_1741782830.png",
    routine: "Rake through wet curls in sections from root to tip, then air dry or diffuse.",
    pairsWith: ["shampoo", "conditioner"],
    blurb: "A silicone-free creme that defines your natural curl texture, reduces frizz and adds shine.<br><br>Enhances, defines & shapes curls Hydrates and softens curls Tames frizz and fly-aways. Chia & Linseed Oils: Work together to form and shape curls, control frizz and help protect hai",
  },
  {
    id: "amika-soulstruck-nourishing-dry-hair-mask",
    name: "Soulstruck Nourishing Dry Hair Mask (30ml)",
    brand: "Amika",
    category: "Hair",
    points: 100,
    tier: "All members",
    covers: ["damage", "hydration"],
    vessel: 4,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_840117815582-AMIKA-Soulstruck-Nourishing-Dry-Hair-Mask_4376f9e4b05073a99632e8f4e3f15bd849491bf5_1775024563.png?o=clean-planet-aware",
    routine: "Smooth evenly through clean, damp hair after shampooing, leave for 5 to 7 minutes, and rinse.",
    pairsWith: ["shampoo", "conditioner"],
  },
  {
    id: "ouai-detox-shampoo",
    name: "Detox Shampoo (30ml)",
    brand: "OUAI",
    category: "Hair",
    points: 100,
    tier: "All members",
    covers: ["scalp", "volume"],
    vessel: 5,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_815402020521-Ouai-Detox-Shampoo-30ml-Default_ff7195a5c4f8ded61a1387f6f20271ecff9ce39f_1659926749.png",
    routine: "Massage into wet hair and scalp once a week instead of regular shampoo, then rinse thoroughly.",
    pairsWith: ["shampoo", "conditioner"],
    caution: "Use once weekly to avoid stripping natural scalp oils.",
    blurb: "Detox Shampoo: This clarifying shampoo deeply cleanses away dirt, oil and product buildup with apple cider vinegar while keratin helps strengthen hair.<br>Detox Shampoo: Clarifying, Cleansing, Removes Buildup, Strengthening<br>CHELATING AGENTS- Helps remove hard water deposits an",
  },
  {
    id: "glow-recipe-toner-pad-collection-trial-set",
    name: "Toner Pad Collection Trial Set",
    brand: "Glow Recipe",
    category: "Skin",
    points: 100,
    tier: "All members",
    covers: ["texture", "brightening", "pores"],
    vessel: 0,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_810052965697-Glow-Recipe-Toner-Pad-Collection-Trial-Se_116a2cce0d1b50ae78d9b2463492330c39550410_1772623497.png?o=clean-planet-aware",
    routine: "Wipe across clean skin after cleansing, tapping remaining essence in before applying serum.",
    pairsWith: ["cleanser", "moisturiser", "spf"],
    conflictsWith: ["retinol", "salicylic", "acid"],
    conflictReason: "Exfoliating pads should not be combined in the same routine with strong retinoids or direct acids.",
    caution: "Introduce gradually if your skin is new to chemical exfoliants.",
    blurb: "Whether your skin needs a smoothing reset, a radiance boost or soothing recovery, these daily Korean Toner Pads transform skin in just 5 minutes..<br><br>We created three types of Toner Pads that are gentle enough to use daily and together for specific skin needs. Smooth, brighte",
  },
  {
    id: "tarte-maracuja-juicy-melt-mask",
    name: "Maracuja Juicy Melt Mask (0.5ml)",
    brand: "tarte",
    category: "Makeup",
    points: 100,
    tier: "All members",
    covers: ["lipcare", "hydration"],
    vessel: 1,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_197689038827-tarte-Maracuja-Juicy-Melt-Mask-0-5ml-Defa_64125d87bb1ce0b957242cdcc812998778fb2203_1738065566.png",
    routine: "Apply liberally over bare lips throughout the day or layer overnight as an intensive lip mask.",
    pairsWith: ["foundation", "lip"],
    blurb: "Viral maracuja juicy lip, now in a juicy melt mask! Keep your lips soft with the melt mask.<br><br>- Juice up your pout with our Pom Pom Power Plumper - it layers just the right amount of product & feels like a cloud on your lips!- gives lips a splash of TLC with 90%+ lip conditi",
  },
  {
    id: "amika-frizz-me-not-hydrating-anti-frizz-trea",
    name: "Frizz-Me-Not Hydrating Anti-Frizz Treatment (30ml)",
    brand: "Amika",
    category: "Hair",
    points: 100,
    tier: "All members",
    covers: ["frizz", "damage"],
    vessel: 2,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_840117814172-AMIKA-Frizz-Me-Not-Hydrating-Anti-Frizz-T_0244ef1922d73e6526c61f614b9b087da8c17466_1749615426.png?o=clean-planet-aware",
    routine: "Mist or smooth evenly through clean, damp hair before blow-drying.",
    pairsWith: ["shampoo", "conditioner"],
    caution: "Heat-activated formula requires blow-drying or heat styling for optimal smoothing.",
    blurb: "A 2-in-1 hydrating leave-in and smoothing treatment that seals in moisture, protects up to 450°F, and locks out frizz for 72 hours* of glossy hair.<br><br>Boost hydration while reducing frizz for up to 72 hours* (even in high humidity!) with this heat-activated treatment for glos",
  },
  {
    id: "it-cosmetics-confidence-in-a-gel-cream",
    name: "Confidence In A Gel Cream (7ml)",
    brand: "IT Cosmetics",
    category: "Skin",
    points: 200,
    tier: "All members",
    covers: ["pores", "hydration", "texture"],
    vessel: 3,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_3605972886354-IT-Cosmetics-Confidence-In-A-Gel-Cream-7_fd6b1c82abecd98dbf2d093c3289239790fcbcb9_1715918250.png",
    routine: "Smooth a pea-sized amount over face and neck morning and night after serums.",
    pairsWith: ["cleanser", "moisturiser", "spf"],
    avoidFor: ["Dry"],
    avoidReason: "Oil-free gel texture is formulated for sebum control and will lack sufficient rich lipids for dry skin.",
    blurb: "It’s your hydrating, oil-free moisturizer for combination and oily skin types. An ultra-light cream that minimizes shine, reduces appearance of pores, corrects uneven skin texture and hydrates skin all in one.<br><br>Beat oil and boost confidence with our daily non-comedogenic mo",
  },
  {
    id: "sol-de-janeiro-rosa-charmosa-dewy-cream",
    name: "Rosa Charmosa™ Dewy Cream (25ml)",
    brand: "Sol de Janeiro",
    category: "Skin",
    points: 200,
    tier: "All members",
    covers: ["hydration", "barrier"],
    vessel: 4,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_810912038394-Sol-De-Janeiro-Rosa-Charmosa--Dewy-Cream-_2e2654449302b83ab46d6c22774b457cf93e360a_1767609950.png",
    routine: "Massage generously all over the body onto clean, dry or towel-damp skin.",
    pairsWith: ["cleanser", "moisturiser", "spf"],
  },
  {
    id: "ouai-santorini-fragrance-mist-eau-de-toilett",
    name: "Santorini Fragrance Mist Eau De Toilette (25ml)",
    brand: "OUAI",
    category: "Hair",
    points: 200,
    tier: "All members",
    covers: ["hydration"],
    vessel: 5,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_815402024178-Ouai-Santorini-Fragrance-Mist-Eau-De-Toil_df6927123b12ac623c4d3888afe59ec86a0172ed_1764065401.png",
    routine: "Spritz generously over hair and body whenever you need an uplifting fragrance refresh.",
    pairsWith: ["shampoo", "conditioner"],
    caution: "Contains fragrance; patch test if you have sensitive skin.",
    blurb: "This Santorini Hair & Body Mist is a deep dive into the light & bright scents of the Mediterranean with notes of peach, orange, honeysuckle & amber.<br><br>Dive all the OUAI in with Santorini Hair & Body Mist. With a light & bright blend of peach, orange, honeysuckle & amber, you",
  },
  {
    id: "sephora-collection-super-glow",
    name: "Super Glow (8ml)",
    brand: "Sephora Collection",
    category: "Skin",
    points: 200,
    tier: "All members",
    covers: ["brightening", "firmness"],
    vessel: 0,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_3378870195346-Sephora-Collection-Super-Glow-8ml-Defaul_f8ee934a5201d32440a4e4a56b8067f726577e01_1747367992.png?o=clean",
    routine: "Apply 3 to 4 drops to clean skin in the morning before moisturiser and sun protection.",
    pairsWith: ["cleanser", "moisturiser", "spf"],
    conflictsWith: ["retinol", "acid"],
    conflictReason: "High concentrations of vitamin C should not be mixed with copper peptides or direct AHA/BHA.",
    caution: "Use SPF during daylight hours to preserve brightening benefits.",
  },
  {
    id: "biossance-squalane-growth-factor-firming-moi",
    name: "Squalane + Growth Factor Firming Moisturizer (5ml)",
    brand: "Biossance",
    category: "Skin",
    points: 200,
    tier: "All members",
    covers: ["firmness", "barrier", "hydration"],
    vessel: 1,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_810029624503-Biossance-Squalane-Growth-Factor-Firming-_049b0a76b332576723608cd34dfd90ed811e934d_1785381788.png?o=clean-planet-aware",
    routine: "Press a dime-sized amount into cleansed face and neck morning and evening after serum.",
    pairsWith: ["cleanser", "moisturiser", "spf"],
    blurb: "This moisturizer visibly firms skin with biomimetic growth factor, a plant-based peptide that improves the look of laxity, fine lines, and bounce.<br><br>Outsmart fine lines with 3 breakthrough biotech ingredients that restore the look of youthful, collagen-rich skin and support ",
  },
  {
    id: "caudalie-instant-detox-mask",
    name: "Instant Detox Mask (15 ML)",
    brand: "Caudalie",
    category: "Skin",
    points: 200,
    tier: "All members",
    covers: ["pores", "texture"],
    vessel: 2,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_3522930034346-Caudalie-Instant-Detox-Mask-15-ML-Defaul_041edb3dcebdd48ead080e957c25159f4c363976_1781632082.png?o=clean-planet-aware",
    routine: "Apply a thin layer to clean skin twice weekly, leave for 5 to 10 minutes, then rinse.",
    pairsWith: ["cleanser", "moisturiser", "spf"],
    avoidFor: ["Dry"],
    avoidReason: "Absorbs surface oil intensely and may leave very dry skin feeling tight or dehydrated.",
    conflictsWith: ["acid", "salicylic"],
    conflictReason: "Avoid using directly alongside strong chemical peels on the same evening.",
    caution: "Do not let the clay fully dry and crack on the face before rinsing.",
    blurb: "Discover the instant detox mask, a super-effective pink clay face mask that purifies the skin, tightens pores and absorbs excess sebum in all skin types.<br><br>Instant detox mask cleanses the skin of all its impurities, eliminates excess sebum and tightens pores. After only 10 m",
  },
  {
    id: "kravebeauty-oat-so-simple-water-cream",
    name: "Oat So Simple Water Cream (20ml)",
    brand: "KraveBeauty",
    category: "Skin",
    points: 200,
    tier: "All members",
    covers: ["barrier", "hydration"],
    vessel: 3,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_850036559283-Kravebeauty-Oat-So-Simple-Water-Cream-20m_aa38e1680835c5fb598cb84d75f8f792840a6138_1729771412.png",
    routine: "Smooth evenly over the face and neck as the final moisturising step morning and night.",
    pairsWith: ["cleanser", "moisturiser", "spf"],
    blurb: "A mini version of our daily, lightweight moisturizer enriched with oat and squalane to soothe irritation and lock in moisture.<br><br>A light-as-water moisturizer now available in a mini size that feels like a burst of refreshing hydration on the face. Formulated with less than 9",
  },
  {
    id: "drunk-elephant-protini-polypeptide-cream",
    name: "Protini Polypeptide Cream (5ml)",
    brand: "Drunk Elephant",
    category: "Skin",
    points: 200,
    tier: "All members",
    covers: ["firmness", "barrier", "hydration"],
    vessel: 4,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_856556004920-Drunk-Elephant-Protini-Polypeptide-Cream-_31fba37e285409e963419ff9caab510cb9619625_1724051359.png?o=clean",
    routine: "Dispense one pump and apply evenly to clean, dry skin morning and evening.",
    pairsWith: ["cleanser", "moisturiser", "spf"],
  },
  {
    id: "tarte-tartelette-xl-tubing-mascara",
    name: "Tartelette™ XL Tubing Mascara (2ml)",
    brand: "tarte",
    category: "Makeup",
    points: 200,
    tier: "All members",
    covers: ["longwear", "volume"],
    vessel: 5,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_197689014289-tarte-Tartelette-XL-Tubing-Mascara-2ml-De_a0ee948530c7770c15786294de813d9716adc492_1719229891.png",
    routine: "Wiggle the wand from lash root to tip, building desired length before the polymer formula sets.",
    pairsWith: ["foundation", "lip"],
    caution: "Remove using warm water and gentle pressure; makeup wipes are ineffective on tubing polymers.",
    blurb: "Revolutionary deluxe XL tubing mascara with 24-hr flake free & smudge proof formula has lengthening “tubes” that wrap lashes for XL length, lift & lash love<br><br>Tubing XL peptide blend for XL length, XL lift & XL pigment.<br>24-hr flake-free, smudge proof & sweatproof.<br>TLC ",
  },
  {
    id: "percy-reed-give-me-strength-strengthening-sh",
    name: "Give Me Strength Strengthening Shampoo (50ml)",
    brand: "Percy & Reed",
    category: "Hair",
    points: 200,
    tier: "All members",
    covers: ["damage", "scalp"],
    vessel: 0,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_5060265375645-Percy-Reed-Give-Me-Strength-Strengthenin_e01156d3a6531db04250952754cc174d08b6101e_1777024401.png",
    routine: "Lather into wet hair and scalp, massage thoroughly, and rinse well before conditioning.",
    pairsWith: ["shampoo", "conditioner"],
  },
  {
    id: "ouai-hair-oil",
    name: "Hair Oil (5ml)",
    brand: "OUAI",
    category: "Hair",
    points: 200,
    tier: "All members",
    covers: ["frizz", "damage"],
    vessel: 1,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_815402020576-OUAI-HAIRCARE-Hair-Oil-5ml-Default_35774eac27df2c5c46a4fdbce2584f0792f61c7d_1661753755.png",
    routine: "Warm 1-2 drops between palms and work through damp lengths before blow-drying, or onto dry ends to finish.",
    pairsWith: ["shampoo", "conditioner"],
    caution: "Start with a single drop; adding too much on fine hair can weigh strands down.",
    blurb: "This ultra-lightweight hair oil is color-safe and provides heat protection while fighting frizz and smoothing hair.<br><br>Provides heat protection up 450°F/232°C.<br>Delivers sleek, frizz-free hair<br>Adds softness, shine and hydration<br>This hair oil is packed with African gal",
  },
  {
    id: "tatcha-the-longevity-memory-cream",
    name: "The Longevity Memory Cream (5ml)",
    brand: "Tatcha",
    category: "Skin",
    points: 250,
    tier: "All members",
    covers: ["firmness", "barrier", "hydration"],
    vessel: 2,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_691835569550-Tatcha-The-Longevity-Memory-Cream-5ml-Def_a38decca2ae2d44dd2dab3631f4337edcf6d5fa8_1764930812.png",
    routine: "Warm a pearl-sized amount between fingertips and gently press into face and neck nightly.",
    pairsWith: ["cleanser", "moisturiser", "spf"],
    avoidFor: ["Oily"],
    avoidReason: "Rich memory-texture cream is intensely emollient and may feel too heavy on oily skin.",
  },
  {
    id: "sol-de-janeiro-brazilian-bum-bum-cream",
    name: "Brazilian Bum Bum Cream (25ml)",
    brand: "Sol de Janeiro",
    category: "Skin",
    points: 250,
    tier: "All members",
    covers: ["firmness", "hydration"],
    vessel: 3,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_810912032026-Sol-De-Janeiro-Brazilian-Bum-Bum-Cream-25ml-Default_0bc90c5a5fbb0c09c115e7bfa49242ea71ecdc3f_1686758334.png",
    routine: "Massage in circular motions over legs, glutes, and arms to boost microcirculation and hydration.",
    pairsWith: ["cleanser", "moisturiser", "spf"],
    caution: "Contains fragrance and shimmer mica; not intended for facial application.",
    blurb: "A fast-absorbing body cream with an addictive scent and a visibly tightening, smoothing formula that adds a hint of shimmer to skin.<br><br>This award-winning, deliciously-scented body cream is the ultimate Brazilian Beauty Secret.<br><br>- Helps visibly smooth and tighten the ap",
  },
  {
    id: "benefit-cosmetics-benetint-cheek-lip-tint",
    name: "Benetint Cheek & Lip Tint (2ml)",
    brand: "Benefit Cosmetics",
    category: "Makeup",
    points: 250,
    tier: "All members",
    covers: ["longwear", "lipcare"],
    vessel: 4,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_602004116284-Benefit-Cosmetics-Benetint-Cheek-Lip-Tint_4c8eb78fc0720974588f6ceedd069feefa19a9e5_1739276698.png",
    routine: "Dot onto the apples of cheeks or brush across lips, blending immediately with fingertips.",
    pairsWith: ["foundation", "lip"],
    caution: "Blends and sets quickly; work on one cheek at a time.",
    blurb: "Benetint Cheek & Lip Tint Individual Sample. A rose-tinted lip and cheek tint.<br><br>This is the sexiest flush you can get from a bottle. This iconic rose-tinted lip stain was created for an exotic dancer in the 1970s, and has since soared to cult-fave status. The precise lip ap",
  },
  {
    id: "sol-de-janeiro-brazilian-crush-cheirosa-62-h",
    name: "Brazilian Crush™ Cheirosa 62 Hair And Body Fragrance Mist (30 ML)",
    brand: "Sol de Janeiro",
    category: "Hair",
    points: 250,
    tier: "All members",
    covers: ["hydration"],
    vessel: 5,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_810912033764-Sol-De-Janeiro-Brazilian-Crush-Cheirosa-6_545571ed335cce91d5d38977ff3e796376daf918_1709188388.png",
    routine: "Mist liberally over hair and body throughout the day for an aromatic boost.",
    pairsWith: ["shampoo", "conditioner"],
    caution: "Contains fragrance; keep away from broken skin or eyes.",
    blurb: "A warm and delicious perfume mist bursting with an alluring pistachio and salted caramel scent.<br><br>Our first crush is the iconic scent that started it all. Like a blend of the best summer you ever had and the best summer you’re about to have. This warm, sunny, beachy scent wi",
  },
  {
    id: "sol-de-janeiro-cheirosa-91-perfume-mist",
    name: "Cheirosa 91 Perfume Mist (30ml)",
    brand: "Sol de Janeiro",
    category: "Hair",
    points: 250,
    tier: "All members",
    covers: ["hydration"],
    vessel: 0,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_810912037083-Sol-De-Janeiro-Cheirosa-91-Perfume-Mist-3_5b3402eb8e489bfc692ca0b925156fa00e92efd6_1767691865.png",
    routine: "Spray evenly onto hair and body as desired for an instant fragrance layer.",
    pairsWith: ["shampoo", "conditioner"],
    caution: "Contains fragrance; spray away from eyes.",
  },
  {
    id: "fresh-fresh-rose-deep-hydration-face-cream",
    name: "Fresh Rose Deep Hydration Face Cream (7ml)",
    brand: "FRESH",
    category: "Skin",
    points: 250,
    tier: "All members",
    covers: ["hydration", "barrier"],
    vessel: 1,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_809280158261-FRESH-Fresh-Rose-Deep-Hydration-Face-Cream-7ml-Default_e33082fa895192880c57f5730f731f3418d5316f_1676437279.png",
    routine: "Apply a 10p-sized amount over face and neck daily, morning and evening after toner.",
    pairsWith: ["cleanser", "moisturiser", "spf"],
    avoidFor: ["Oily"],
    avoidReason: "Rich lipid-heavy formulation is designed for parched skin and may exacerbate excess oil.",
  },
  {
    id: "caudalie-vinopure-blemish-control-salicylic-",
    name: "Vinopure Blemish Control Salicylic Serum (10ml)",
    brand: "Caudalie",
    category: "Skin",
    points: 300,
    tier: "All members",
    covers: ["pores", "texture"],
    vessel: 2,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_3522933005008-Caudalie-Vinopure-Blemish-Control-Salicy_9d735d12fecd2140d7bb92998fceb30082b7e082_1750161069.png?o=clean-planet-aware",
    routine: "Apply 2 to 3 drops to clean skin morning and evening before your moisturiser.",
    pairsWith: ["cleanser", "moisturiser", "spf"],
    avoidFor: ["Dry"],
    avoidReason: "Formulated with clarifying salicylic acid that can strip moisture from dry or compromised barriers.",
    conflictsWith: ["retinol", "acid"],
    conflictReason: "Avoid simultaneous layering with strong retinol or prescription retinoids to prevent peeling.",
    caution: "Wear sunscreen during daytime use; reduce application frequency if flaking occurs.",
    blurb: "The Vinopure Blemish Control Salicylic Serum, with natural salicylic acid, reduces all types of blemishes (breakouts, pores, blackheads) with no rebound effect and while preserving the skin barrier. It unclogs and tightens pores while refining skin texture. Formulated with natura",
  },
  {
    id: "percy-reed-session-styling-volumising-mousse",
    name: "Session Styling Volumising Mousse (50 ML)",
    brand: "Percy & Reed",
    category: "Hair",
    points: 300,
    tier: "All members",
    covers: ["volume", "longwear"],
    vessel: 3,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_5060265375638-Percy-Reed-Session-Styling-Volumising-Mo_c4cf0564138188573577e581132ed425809ce38f_1776678768.png",
    routine: "Dispense a golf-ball-sized amount into palms and distribute through damp roots before blow-drying.",
    pairsWith: ["shampoo", "conditioner"],
    caution: "Distribute evenly to avoid localised stiffness.",
  },
  {
    id: "benefit-cosmetics-gimme-brow-brow-volumizing",
    name: "Gimme Brow+ Brow-Volumizing Gel (1g)",
    brand: "Benefit Cosmetics",
    category: "Makeup",
    points: 300,
    tier: "All members",
    covers: ["volume", "coverage"],
    vessel: 4,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_602004161413-Benefit-Cosmetics-Gimme-Brow-Brow-Volumiz_e6d3a5764f96e2cdf47254717ea26fa3d205c635_1739276277.png",
    routine: "Stroke the precision tip along brows to shape, tint, and build volume.",
    pairsWith: ["foundation", "lip"],
  },
  {
    id: "benefit-cosmetics-badgal-bounce-mascara-pump",
    name: "BADgal Bounce Mascara - Pump’d Up Black (3g)",
    brand: "Benefit Cosmetics",
    category: "Makeup",
    points: 300,
    tier: "All members",
    covers: ["volume", "longwear"],
    vessel: 5,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_602004157102-Benefit-Cosmetics-BADgal-Bounce-Mascara-P_4659ddc9677c43a9fb10895c39a9b9cd12d4f22c_1739276610.png",
    routine: "Comb through lashes from base to tip in gentle zig-zag motions for high-impact volume.",
    pairsWith: ["foundation", "lip"],
  },
  {
    id: "ouai-leave-in-conditioner",
    name: "Leave In Conditioner (25ml)",
    brand: "OUAI",
    category: "Hair",
    points: 300,
    tier: "All members",
    covers: ["frizz", "hydration", "damage"],
    vessel: 0,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_193302_20Ouai_20Leave_20In_20Conditioner_20Deluxe_2025ml_70537ff681a7b1fbcede839afef0f91180a356f6_1532331127.png",
    routine: "Mist over towel-dried hair from mid-lengths to ends, then comb through before styling.",
    pairsWith: ["shampoo", "conditioner"],
    blurb: "A hydrating leave-in conditioner and detangler with thermal protection to reduce frizz and flyaways for perfectly smooth, silky hair.",
  },
  {
    id: "benefit-cosmetics-24-hr-brow-setter-invisibl",
    name: "24-Hr Brow Setter Invisible Brow Gel - 2ml",
    brand: "Benefit Cosmetics",
    category: "Makeup",
    points: 300,
    tier: "All members",
    covers: ["longwear"],
    vessel: 1,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_602004129642-Benefit-Cosmetics-24-Hr-Brow-Setter-Invisible-Brow-Gel---2ml-Default_4c9b5a7d8b024265cf0f33cc362d7fd4f7beb25b_1621517402.png",
    routine: "Brush through brows using the dual-sided applicator to style and set hairs in place.",
    pairsWith: ["foundation", "lip"],
    caution: "Allow to dry completely before touching brows.",
  },
  {
    id: "shiseido-global-suncare-the-perfect-protecto",
    name: "Global Suncare The Perfect Protector SPF 50+/PA++++ (15ml)",
    brand: "Shiseido",
    category: "Skin",
    points: 300,
    tier: "All members",
    covers: ["barrier", "hydration"],
    vessel: 2,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_729238081482-Shiseido-Global-Suncare-The-Perfect-Prote_55205fca21300422a9c5df12cabc821f166173d2_1744718748.png",
    routine: "Smooth generously over face and neck as the final step of your morning skincare routine.",
    pairsWith: ["cleanser", "moisturiser", "spf"],
    caution: "Reapply every 2 hours when swimming or sweating.",
  },
  {
    id: "clinique-moisture-surge-100h-auto-replenishi",
    name: "Moisture Surge 100H Auto-Replenishing Hydrator Moisturiser (15 ml)",
    brand: "Clinique",
    category: "Skin",
    points: 500,
    tier: "Gold & Black",
    covers: ["hydration", "barrier"],
    vessel: 3,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_192333067406-Clinique-Moisture-Surge-100H-Auto-Replenishing-Hydrator-15-ml-Default_108edc1300e22c9258933fc2eb15798e22f46d93_1626892485.png",
    routine: "Apply morning and evening to clean skin, or tap over makeup as a midday hydration boost.",
    pairsWith: ["cleanser", "moisturiser", "spf"],
  },
  {
    id: "dr-dennis-gross-alpha-beta-extra-strength-da",
    name: "Alpha Beta® Extra Strength Daily Peel (3 Treatments)",
    brand: "Dr. Dennis Gross",
    category: "Skin",
    points: 500,
    tier: "Gold & Black",
    covers: ["texture", "brightening", "pores"],
    vessel: 4,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_695866582861-DR-DENNIS-GROSS-Alpha-Beta-Extra-Strength-Daily-Peel-3-Treatments-Defau_618b2274b3c43463034ac36dce0010cecdc07a0f_1666279713.png",
    routine: "Massage Step 1 pad over clean, dry skin until dry, wait 2 minutes, then follow with Step 2.",
    pairsWith: ["cleanser", "moisturiser", "spf"],
    avoidFor: ["Dry"],
    avoidReason: "High concentration of mixed acids can severely disrupt dry or compromised skin barriers.",
    conflictsWith: ["retinol", "salicylic", "acid", "vitamin c"],
    conflictReason: "Do not combine in the same routine with other direct acids, retinoids, or strong physical scrubs.",
    caution: "Expect a mild tingling sensation; always use broad-spectrum SPF daily.",
    blurb: "A fast-acting, two-step daily treatment for clinical results at home. Our<br>strongest dose of 7 AHA/BHAs plus antioxidants and vitamins lift away<br>dead skin along with excess oil & impurities, while improving uneven<br>tone & texture.<br>2 minutes to smooth, beautiful skin. Ex",
  },
  {
    id: "dr-dennis-gross-alpha-beta-universal-daily-p",
    name: "Alpha Beta® Universal Daily Peel (3 Treatments)",
    brand: "Dr. Dennis Gross",
    category: "Skin",
    points: 500,
    tier: "Gold & Black",
    covers: ["texture", "brightening", "pores"],
    vessel: 5,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_695866581468-DR-DENNIS-GROSS-Alpha-Beta-Universal-Daily-Peel-3-Treatments-Default_856e65950090415cc46f9ff9f4a15f4703d8af75_1666279711.png",
    routine: "Wipe Step 1 over clean, dry skin, wait 2 minutes, then apply Step 2 before serums.",
    pairsWith: ["cleanser", "moisturiser", "spf"],
    avoidFor: ["Dry"],
    avoidReason: "Daily AHA/BHA combination can cause excess dryness if your skin lacks adequate sebum.",
    conflictsWith: ["retinol", "salicylic", "acid"],
    conflictReason: "Do not layer directly with strong retinol or other leave-on chemical exfoliants.",
    caution: "Always apply daytime sun protection while using exfoliating acids.",
    blurb: "A fast-acting, two-step daily treatment for clinical results at home. Our effective dose of 5 AHA/BHAs plus antioxidants and vitamins lift away dead skin along with excess oil & impurities, while improving uneven tone & texture.<br>2 minutes to smooth, beautiful skin. Experience ",
  },
  {
    id: "shiseido-ultimune-power-infusing-serum",
    name: "Ultimune Power Infusing Serum (10ml)",
    brand: "Shiseido",
    category: "Skin",
    points: 500,
    tier: "Gold & Black",
    covers: ["barrier", "firmness", "hydration"],
    vessel: 0,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_729238078932-Shiseido-Ultimune-Power-Infusing-Serum-10_18a3eadc240a53ac2644d5d4c2b48f400391810a_1739189754.png",
    routine: "Smooth two pumps over face and neck morning and night after cleansing and softening.",
    pairsWith: ["cleanser", "moisturiser", "spf"],
  },
  {
    id: "sephora-beauty-pass-exclusive-10-off",
    name: "10% Off",
    brand: "Sephora Beauty Pass Exclusive",
    category: "Skin",
    points: 500,
    tier: "All members",
    covers: ["hydration"],
    vessel: 1,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_3378878314176-Sephora-Beauty-Pass-Exclusive_3d44c8918366c0c93728e4c4fb5951d289efc614_1604908565.png",
    routine: "Apply the reward coupon at checkout online or present in-store on qualifying items.",
    pairsWith: ["cleanser", "moisturiser", "spf"],
    caution: "Valid on eligible purchases for registered Beauty Pass members only.",
    blurb: "Limit of one coupon per transaction. Rewards are valid with 500 Beauty Pass points with a purchase. Must be a registered Beauty Pass member to redeem reward. Not applicable to purchases of gift cards or services. Not stackable with other discounts or promotions. Non-refundable.",
  },
  {
    id: "augustinus-bader-the-sunscreen-spf-50-pa",
    name: "The Sunscreen SPF 50 PA ++++ (7ml)",
    brand: "Augustinus Bader",
    category: "Skin",
    points: 750,
    tier: "Gold & Black",
    covers: ["barrier", "hydration"],
    vessel: 2,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_5060990632549-AUGUSTINUS-BADER-The-Sunscreen-SPF-50-PA_35130001c08342fd417cfd88c3fc110421eac16c_1742385400.png",
    routine: "Apply liberally to face and neck as the final step in your morning skincare routine.",
    pairsWith: ["cleanser", "moisturiser", "spf"],
    caution: "Reapply every 2 hours during continuous sun exposure.",
    blurb: "Suncare meets skincare in this lightweight, broad-spectrum sunscreen. The fast-absorbing, clean formula powered by TFC8® both protects against UVA and UVB rays and renews the skin, preventing and reducing visible signs of aging. Your daily SPF 50. Powered by TFC8®.<br><br>\"Offers",
  },
  {
    id: "allies-of-skin-multi-peptides-gf-advanced-li",
    name: "Multi Peptides & GF Advanced Lifting Serum (7ml)",
    brand: "Allies of Skin",
    category: "Skin",
    points: 1000,
    tier: "Gold & Black",
    covers: ["firmness", "barrier", "texture"],
    vessel: 3,
    image: "https://image-optimizer-reg.production.sephora-asia.net/images/product_images/1_GWP_8885014075471-Allies-of-Skin-Multi-Peptides-GF-Advance_367d5cdd6d31f1eb3de4db787fd761d350bfb7e5_1737115345.png",
    routine: "Press 1 to 2 pumps into clean skin morning and evening before your moisturiser.",
    pairsWith: ["cleanser", "moisturiser", "spf"],
    conflictsWith: ["acid", "vitamin c"],
    conflictReason: "Avoid layering immediately with direct high-strength L-ascorbic acid to avoid peptide destabilisation.",
  },
];

export interface Ingredient {
  name: string;
  note: string;
}

/** Short actives read-out shown in Quick view. */
export const rewardIngredients: Record<string, Ingredient[]> = {
  "pixi-glow-tonic-exfoliating-toner": [
    { name: "Glycolic Acid (5%)", note: "Exfoliates dead surface skin cells to refine texture and boost radiance." },
    { name: "Ginseng", note: "Energises and promotes healthy circulation for a brighter complexion." },
    { name: "Aloe Vera", note: "Soothes and hydrates to mitigate potential irritation." },
  ],
  "ouai-anti-frizz-cr-me": [
    { name: "Squalane", note: "Locks in moisture and smoothes the hair cuticle to prevent humidity-induced frizz." },
    { name: "Shea Butter", note: "Deeply conditions coarse strands and enhances natural shine." },
  ],
  "fresh-soy-face-cleanser": [
    { name: "Soy Proteins", note: "Rich in amino acids to help maintain skin elasticity and suppleness." },
    { name: "Cucumber Extract", note: "Calms and cools reactive or sensitive skin." },
    { name: "Rosewater", note: "Tones, calms, and balances the natural moisture barrier." },
  ],
  "ouai-hair-curl-cr-me": [
    { name: "Chia Seed Oil", note: "Nourishes and shapes curl patterns while blocking out humidity." },
    { name: "Linseed Oil", note: "Adds flexible hold, natural shine, and elasticity to curls." },
    { name: "Babassu Oil", note: "Softens dry texture without weighing down finer wave patterns." },
  ],
  "amika-soulstruck-nourishing-dry-hair-mask": [
    { name: "Sea Buckthorn Berry", note: "Rich in omega-7 fatty acids to deeply nourish and restore strand elasticity." },
    { name: "Jojoba Seed Oil", note: "Penetrates the hair follicle to condition and hydrate brittle ends." },
  ],
  "ouai-detox-shampoo": [
    { name: "Apple Cider Vinegar", note: "Clarifies mineral deposits and dissolves stubborn product build-up." },
    { name: "Hydrolysed Keratin", note: "Fills in hair shaft cracks to fortify and repair weakened strands." },
    { name: "Chelating Agents", note: "Neutralise hard water residue that leaves hair dull and limp." },
  ],
  "glow-recipe-toner-pad-collection-trial-set": [
    { name: "PHA & BHA Complex", note: "Unclogs congested pores and gently buffs rough texture without stripping." },
    { name: "Watermelon Extract", note: "Infuses skin with essential vitamins and plumping hydration." },
    { name: "Centella Asiatica", note: "Soothes active irritation and supports a balanced barrier." },
  ],
  "tarte-maracuja-juicy-melt-mask": [
    { name: "Maracuja Oil", note: "Rich in essential fatty acids to deeply condition and plump dry lips." },
    { name: "Hyaluronic Acid", note: "Attracts and locks in surface moisture for a smooth, cushiony finish." },
    { name: "Grapeseed Oil", note: "Nourishes and protects the delicate lip barrier from environmental drying." },
  ],
  "amika-frizz-me-not-hydrating-anti-frizz-trea": [
    { name: "Sea Buckthorn Oil", note: "Protects the hair cuticle against thermal damage up to 232°C." },
    { name: "Polymer Shield Complex", note: "Repels airborne moisture to lock out frizz for up to 72 hours." },
  ],
  "it-cosmetics-confidence-in-a-gel-cream": [
    { name: "Niacinamide", note: "Regulates sebum production and visibly refines enlarged pores." },
    { name: "Squalane", note: "Provides weightless hydration without clogging pores or leaving residue." },
    { name: "Peptides", note: "Support skin elasticity and smooth uneven surface texture." },
  ],
  "sol-de-janeiro-rosa-charmosa-dewy-cream": [
    { name: "Cupuaçu Butter", note: "Locks in deep moisture and restores skin elasticity." },
    { name: "Hyaluronic Acid", note: "Delivers plumping hydration to the superficial skin layers." },
    { name: "Rosehip Oil", note: "Nourishes and leaves a soft, luminous dewy sheen across the body." },
  ],
  "ouai-santorini-fragrance-mist-eau-de-toilett": [
    { name: "Glycerin", note: "Draws moisture into the hair and skin surface." },
    { name: "Fragrance Composition", note: "Scent notes of crisp peach, Mediterranean orange blossom, and amber." },
  ],
  "sephora-collection-super-glow": [
    { name: "Vitamin C (Ascorbyl Glucoside)", note: "Evens out pigmentation and revives dull skin tone." },
    { name: "Vitamin E", note: "Provides antioxidant support to combat environmental stressors." },
    { name: "Peptides", note: "Help support natural collagen synthesis for firmer-looking skin." },
  ],
  "biossance-squalane-growth-factor-firming-moi": [
    { name: "Biomimetic Growth Factor", note: "Signals cellular turnover to visibly firm skin laxity and plump lines." },
    { name: "Sugarcane Squalane", note: "Mimics natural skin lipids to deeply hydrate and protect the barrier." },
    { name: "Niacinamide", note: "Improves elasticity and smooths uneven skin tone." },
  ],
  "caudalie-instant-detox-mask": [
    { name: "Pink Clay", note: "Draws out impurities and absorbs excess sebum from congested pores." },
    { name: "Grape Marc Extract", note: "Provides soothing antioxidant protection against free radical damage." },
    { name: "Coffee Extract", note: "Decongests and energises skin for a refined, clarified finish." },
  ],
  "kravebeauty-oat-so-simple-water-cream": [
    { name: "Oat Extract (Avena Sativa)", note: "Instantly calms irritation, redness, and sensitivity." },
    { name: "Squalane", note: "Replenishes essential moisture without heaviness or pore-clogging film." },
  ],
  "drunk-elephant-protini-polypeptide-cream": [
    { name: "Signal Peptide Complex (9 Peptides)", note: "Binds moisture to skin while visibly restoring bounce and firmness." },
    { name: "Pygmy Waterlily Stem Cell Extract", note: "Provides intense antioxidant replenishing support to soothe stressed skin." },
    { name: "Soybean Folic Acid Ferment", note: "Helps maintain skin elasticity and protects against environmental stress." },
  ],
  "tarte-tartelette-xl-tubing-mascara": [
    { name: "Tubing Copolymers", note: "Form smudge-proof, 360-degree tubes around each individual lash." },
    { name: "Niacinamide", note: "Conditions and fortifies brittle lashes from root to tip." },
    { name: "Biotin", note: "Supports healthy-looking, stronger lash fibres over time." },
  ],
  "percy-reed-give-me-strength-strengthening-sh": [
    { name: "Biotin", note: "Fortifies fragile strands to reduce breakage and support strand density." },
    { name: "Wheat Protein", note: "Penetrates hair fibres to strengthen structural integrity from within." },
    { name: "Caffeine", note: "Stimulates the scalp microcirculation to support healthy hair growth." },
  ],
  "ouai-hair-oil": [
    { name: "Ama Oil", note: "Shields hair fibres from humidity and environmental moisture loss." },
    { name: "Borage Oil", note: "Smooths flyaways and seals split ends with radiant shine." },
    { name: "Galanga Root Extract", note: "Protects colour vibrancy from UV-induced degradation." },
  ],
  "tatcha-the-longevity-memory-cream": [
    { name: "Japanese Mountain Yam", note: "Helps visibly boost elasticity and skin density." },
    { name: "Hadasei-3 Complex", note: "Fermented trinity of green tea, rice, and algae to restore barrier health." },
    { name: "Squalane", note: "Delivers long-lasting lipid hydration to dry and mature skin." },
  ],
  "sol-de-janeiro-brazilian-bum-bum-cream": [
    { name: "Guaraná Extract", note: "Delivers potent caffeine to help visibly smooth and tighten skin texture." },
    { name: "Cupuaçu Butter", note: "Provides fatty acids to lock in moisture and bolster the skin barrier." },
    { name: "Açaí Oil", note: "Delivers antioxidant power to protect skin against environmental damage." },
  ],
  "benefit-cosmetics-benetint-cheek-lip-tint": [
    { name: "Rose Centifolia Flower Extract", note: "Provides natural floral hydration and subtle botanical scent." },
    { name: "Staining Pigments", note: "Deliver a smudge-proof, transfer-resistant flush of sheer rosy tint." },
  ],
  "sol-de-janeiro-brazilian-crush-cheirosa-62-h": [
    { name: "Glycerin", note: "Maintains lightweight surface moisture without residue." },
    { name: "Fragrance Blend", note: "Gourmand profile of salted caramel, pistachio, and vanilla." },
  ],
  "sol-de-janeiro-cheirosa-91-perfume-mist": [
    { name: "Glycerin", note: "Conditions hair and skin lightly without weighing down styling." },
    { name: "Fragrance Blend", note: "Warm tropical scent profile designed for hair and skin application." },
  ],
  "fresh-fresh-rose-deep-hydration-face-cream": [
    { name: "Damask Rose Extract", note: "Strengthens the moisture barrier and locks in multi-depth hydration." },
    { name: "Hyaluronic Acid", note: "Plumps skin surface with sustained, 72-hour moisture." },
    { name: "Rosewater", note: "Calms, tones, and leaves skin refreshed and supple." },
  ],
  "caudalie-vinopure-blemish-control-salicylic-": [
    { name: "Natural Salicylic Acid (BHA)", note: "Penetrates deep into pores to dissolve excess sebum and reduce blemishes." },
    { name: "Niacinamide", note: "Soothes inflammation, refines skin texture, and balances oil." },
    { name: "Grape Polyphenols", note: "Provide antioxidant defence to prevent sebum oxidation and blackheads." },
  ],
  "percy-reed-session-styling-volumising-mousse": [
    { name: "Styling Polymers", note: "Provide lasting root lift and flexible, touchable body without crunch." },
    { name: "Panthenol (Pro-Vitamin B5)", note: "Boosts strand moisture and shields against styling dehydration." },
  ],
  "benefit-cosmetics-gimme-brow-brow-volumizing": [
    { name: "Microfibres", note: "Adhere to existing brow hairs to create natural-looking fullness and density." },
    { name: "Marshmallow Root Extract", note: "Conditions brow hair while providing flexible, water-resistant hold." },
  ],
  "benefit-cosmetics-badgal-bounce-mascara-pump": [
    { name: "Castor Seed Oil", note: "Conditions lashes to keep them flexible and flake-free." },
    { name: "Volume Wax Blend", note: "Builds dramatic lash volume and gravity-defying lift without clumping." },
  ],
  "ouai-leave-in-conditioner": [
    { name: "Tamarind Seed Extract", note: "Provides weightless, velvety hydration comparable to hyaluronic acid." },
    { name: "Panthenol", note: "Strengthens hair shafts and defends against heat damage up to 232°C." },
    { name: "Vitamin E", note: "Shields strands from environmental pollution and UV-induced oxidation." },
  ],
  "benefit-cosmetics-24-hr-brow-setter-invisibl": [
    { name: "Dual-Sided Polymer Complex", note: "Locks brow hairs securely in place for up to 24 hours without flaking." },
    { name: "Silk Proteins", note: "Condition and add a clean, flexible sheen to brow hairs." },
  ],
  "shiseido-global-suncare-the-perfect-protecto": [
    { name: "WetForce & HeatForce Polymers", note: "Strengthen the protective UV veil when exposed to water, sweat, and heat." },
    { name: "Profence CEL Complex", note: "Shields skin against photo-ageing, wrinkles, and dark spots." },
  ],
  "clinique-moisture-surge-100h-auto-replenishi": [
    { name: "Aloe Bio-Ferment", note: "Delivers nutrient-dense hydration that penetrates deep into skin layers." },
    { name: "Hyaluronic Acid", note: "Draws and holds moisture for a plumper, dewy complexion." },
    { name: "Activated Aloe Water", note: "Enhances skin's receptivity and absorption of hydration." },
  ],
  "dr-dennis-gross-alpha-beta-extra-strength-da": [
    { name: "Glycolic & Lactic Acids (AHA)", note: "Exfoliate dead surface cells to dramatically smooth uneven texture." },
    { name: "Salicylic Acid (BHA)", note: "Penetrates deep into pores to dissolve trapped sebum and debris." },
    { name: "Resveratrol & Green Tea", note: "Potent antioxidants in Step 2 that neutralise acid activity and calm skin." },
  ],
  "dr-dennis-gross-alpha-beta-universal-daily-p": [
    { name: "5 AHA/BHA Blend", note: "Gently dissolves cellular debris to refine texture and unclog pores." },
    { name: "Chamomile Extract", note: "Soothes surface redness and mitigates post-exfoliation irritation." },
    { name: "Green Tea Extract", note: "Calms the skin barrier in Step 2 while delivering free-radical defence." },
  ],
  "shiseido-ultimune-power-infusing-serum": [
    { name: "Fermented Roselle Extract", note: "Stimulates skin's internal defence system against environmental stressors." },
    { name: "Heartleaf Extract", note: "Soothes active irritation and reinforces compromised skin barriers." },
    { name: "Reishi Mushroom Extract", note: "Rich in antioxidants to visibly reduce signs of ageing and fatigue." },
  ],
  "sephora-beauty-pass-exclusive-10-off": [
    { name: "Beauty Pass Discount", note: "One-time 10% discount redemption applied directly at checkout." },
  ],
  "augustinus-bader-the-sunscreen-spf-50-pa": [
    { name: "TFC8® Complex", note: "Proprietary cellular renewal blend that guides key nutrients to skin cells." },
    { name: "Zinc Oxide & Chemical UV Filters", note: "Provide broad-spectrum SPF 50 protection against UVA/UVB damage." },
    { name: "Saguaro Cactus Extract", note: "Combats environmental pollutants and calms sun-exposed skin." },
  ],
  "allies-of-skin-multi-peptides-gf-advanced-li": [
    { name: "Growth Factor Complex", note: "Promotes cellular rejuvenation and visibly lifts sagging facial contours." },
    { name: "Multiple Peptides (Copper Tripeptide & Palmitoyl)", note: "Stimulate structural collagen production to soften deep lines." },
    { name: "Phospholipids & Squalane", note: "Strengthen the lipid barrier to prevent transepidermal moisture loss." },
  ],
};

export const rewardTerms =
  "While supplies last. Quantities of each reward are limited. Limit of one per customer per transaction. Rewards are valid with Beauty Pass points with a purchase. Non-transferable. Must be a registered Beauty Pass member to redeem. No returns or exchanges.";
